server:
  port: 8084
  
spring:
  data:
    mongodb:
      uri: mongodb+srv://leonel:leonel@cluster0.we5wo.mongodb.net/bank
      
eureka:
  client:
    service-url:
        defaultZone: http://localhost:8096/eureka
  instance:
    preferIpAddress: true
