server:
  port: 8092
  
restClient:
  accountUrl: http://gateway-server-service/api/account 
  creditUrl: http://gateway-server-service/api/credit
  loanUrl: http://gateway-server-service/api/loan
  transactionUrl: http://gateway-server-service/api/transaction

eureka:
  client:
    service-url:
      defaultZone:
        http://localhost:8096/eureka
  instance:
    preferIpAddress: true